import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>GSP Lizzana</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>


                {/* jumbotron */}
                <section id='jumbotron' className='bg-gray-300'>
                    <div className="container mx-auto">
                        <div className='px-4 pt-80 pb-6 sm:pb-12'>
                            <h2 className='text-4xl text-primary font-bold'>23 edizione</h2>
                            <h5 className='text-2xl text-white font-bold mt-3'>Calcio Splash Lizzana</h5>
                            <h5 className='text-2xl text-white font-bold'>Dal 10 al 13 agosto 2023</h5>
                        </div>
                    </div>

                </section>

                {/* register */}
                <section id='register' className='bg-gray-50'>
                    <div className="container mx-auto ">
                        <div className='px-4 py-10 sm:py-16 max-w-xl'>
                            <h5 className='text-2xl font-bold'>
                                Il <span className='text-primary'>Mondiale</span> Si gioca sul gonfiabile
                            </h5>

                            <p className='mt-4'>Sai la differenza tra i mondiali classici e queilli sul sapone? quelli sul sapone non cambiano logo da 4 anni.</p>

                            <div className='w-72'>
                                <button className='block rounded-full bg-primary w-5/6 py-2 mt-8 text-white inline-block'>iscriviti</button>
                            </div>

                        </div>
                    </div>
                </section>

            </main>
        </>
    )
}
